# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

# Set limit for four million
limit = 4000000

# Create array with our start values
start = [1, 2]
# This creates a block with our added values, until
# we reach our limit (four limit)
while start[-2] + start[-1] < limit
  start << start[-2] + start[-1]
end

result = 0

# we need only values added, which are even
start.each { |x| result += x if x.even? }

puts ("Sum: #{result}")